GeneratedException: use mere strings for package names
Some exceptions may be defined in Ada packages whose name violate the
"one word, starting upper case" principle. Use mere strings instead of
names.Name there to avoid violating this principle.

TN: V126-009